In [1]:
import numpy as np
import pandas as pd

## Question 1
What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.20.3'

## Question 2

What's the version of Pandas?

In [3]:
pd.__version__

'1.2.4'

## Load data

In [4]:
data = pd.read_csv('data/data-week1.csv')
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Check data

In [5]:
data.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [6]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 3

What's the average price of BMW cars in the dataset?

In [7]:
makers_list = data['Make'].value_counts()
makers_list

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Spyker    

In [8]:
Q3_samples = data[data['Make'] == 'BMW']

In [9]:
BMW_average = Q3_samples['MSRP'].mean()
BMW_average

61546.76347305389

## Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [10]:
Q4_samples = data[data['Year'] > 2014]

In [11]:
Q4_samples.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 5

#### Calculate the average "Engine HP" in the dataset.

In [12]:
EngineHP_average = data['Engine HP'].mean()
round(EngineHP_average)

249

#### Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [13]:
data['Engine HP'].isnull().sum()

69

In [14]:
data['Engine HP'] = data['Engine HP'].fillna(EngineHP_average)

In [15]:
data['Engine HP'].isnull().sum()

0

#### Now, calcualte the average of "Engine HP" again.

In [16]:
EngineHP_average_new = data['Engine HP'].mean()
round(EngineHP_average_new)

249

#### Has it changed?

<font color='red'>NO</font>

## Question 6

#### Select all the "Rolls-Royce" cars from the dataset.

In [17]:
Q6_samples = data[data['Make'] == 'Rolls-Royce']

In [19]:
Q6_samples.shape

(31, 16)

#### Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

In [22]:
Q6_samples_3cols = Q6_samples[['Engine HP', 'Engine Cylinders', 'highway MPG']]
Q6_samples_3cols.shape

(31, 3)

#### Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

In [23]:
Q6_samples_3cols_unique = Q6_samples_3cols.drop_duplicates()
Q6_samples_3cols_unique.shape

(7, 3)

#### Get the underlying NumPy array. Let's call it X.

In [24]:
X = Q6_samples_3cols_unique.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

#### Compute matrix-matrix multiplication between the transpose of X and X.
To get the transpose, use X.T. Let's call the result XTX.

In [25]:
XTX = np.dot(X.T, X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

#### Invert XTX.

In [26]:
XTXI = np.linalg.inv(XTX)
XTXI

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

#### What's the sum of all the elements of the result?

In [27]:
XTXI.sum()

0.032212320677486125

## Questions 7

#### Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

In [30]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [35]:
w = np.dot( XTXI.dot(X.T), y )
w.shape

(3,)

#### What's the value of the first element of w?.

In [37]:
w[0]

0.19989598183188972